name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: test
        run: |
          npm i
          npm run test
      - name: Jest Reporter
        uses: tanmen/jest-reporter@v1.5
        with:
          # Github Token
          github-token: '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'
          # jest result file path for json
          result-file: # optional, default is result.json
          # Display name. Make sure this name is unique within the workflow.
          action-name: # optional, default is Jest Test Results
